- include_vars: vars/main.yml

- block:
    - name: Update Homebrew on macOS
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
      when: ansible_os_family == "Darwin"
      become: true
      become_user: "{{ local_user }}"

    - name: Debug message for Homebrew installation
      debug:
        msg: "Homebrew installed on {{ ansible_os_family }}"
      when: ansible_os_family == "Darwin"
      become: true
      become_user: "{{ local_user }}"

    - name: Update APT cache on Debian-based systems
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Debug message for APT cache update
      debug:
        msg: "APT cache updated on {{ ansible_os_family }}"
      when: ansible_os_family == "Debian"

    - name: Update Homebrew on macOS
      community.general.homebrew:
        update_homebrew: true
      when: ansible_os_family == "Darwin"
      become: true
      become_user: "{{ local_user }}"

    - name: Debug message for Homebrew update
      debug:
        msg: "Homebrew updated on {{ ansible_os_family }}"
      when: ansible_os_family == "Darwin"

    - name: Debug message for setting configuration directory
      debug:
        msg: "Setting configuration directory to {{ temp_config_dir }}"

    - name: Create temporary configuration directory if not present
      ansible.builtin.file:
        path: "{{ temp_config_dir }}"
        state: directory
        mode: 0755

    - name: Download configuration files from GitHub
      git:
        repo: "{{ github_config_repo_url }}"
        dest: "{{ temp_config_dir }}"
        clone: yes
        update: yes
      become: true
      become_user: "{{ local_user }}"
