neovim_config_repo: "https://github.com/itsvinayak/TurboNvimConfig.nvim.git"
cli_tools:
  - git
  - curl
  - wget
  - btop
  - tree
  - jq
  - fzf
  - ripgrep
  - fd-find
  - bat
  - lsd
  - python3-dev
  - python3-pip
  - python3-setuptools
  - python3-venv
  - python3-full
pip_tools:
  - thefuck
  - pyright
  - pylint
npm_tools:
  - typescript-language-server
  - pm2
  - jshint
  - eslint
