---
- block:
    - name: Ensure Cargo is installed
      ansible.builtin.package:
        name: cargo
        state: present
        update_cache: yes

    - name: Install Alacritty using Cargo
      ansible.builtin.command:
        cmd: cargo install alacritty --locked
        creates: /home/{{ local_user }}/.cargo/bin/alacritty
      become_user: "{{ local_user }}"

    - name: Check if Alacritty is installed
      ansible.builtin.command:
        cmd: alacritty --version
      register: alacritty_version
      failed_when: alacritty_version.rc != 0
      changed_when: false
      ignore_errors: true

    - name: Check if Alacritty configuration file exists
      ansible.builtin.stat:
        path: /home/{{ local_user }}/.config/alacritty/alacritty.yml
      register: alacritty_config
      become: yes
      become_user: "{{ local_user }}"

    - name: Create Alacritty configuration directory
      ansible.builtin.file:
        path: /home/{{ local_user }}/.config/alacritty
        state: directory
        mode: "0755"
      become: yes
      become_user: "{{ local_user }}"
      when: alacritty_config.stat.exists == false

    - name: Copy Alacritty configuration file
      ansible.builtin.copy:
        src: ../../../config/alacritty/alacritty.yml
        dest: /home/{{ local_user }}/.config/alacritty/alacritty.yml
        mode: "0644"
      become: yes
      become_user: "{{ local_user }}"
      when: ansible_os_family in ["Debian", "Darwin"]
