---
- block:
    - name: Add the mmstick76/alacritty PPA (focal)
      apt_repository:
        repo: "{{ alacritty_ppa }}"
        state: present
        codename: focal
      register: add_alacritty_ppa_result
      ignore_errors: yes
      when: ansible_os_family == "Debian"

    - name: Updating apt update
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      when: ansible_os_family == "Debian" and add_alacritty_ppa_result is succeeded

    - name: Installing Alacritty on ubuntu
      ansible.builtin.apt:
        name: alacritty
        state: present
        update_cache: yes
      become: yes
      when: ansible_os_family == "Debian" and add_alacritty_ppa_result is succeeded

    - name: Installing Alacritty on macOS
      community.general.homebrew:
        name: alacritty
        state: present
      become: yes
      when: ansible_os_family == "Darwin"

    - name: Check if Alacritty is installed
      ansible.builtin.command: alacritty --version
      register: alacritty_version
      failed_when: alacritty_version.rc != 0
      changed_when: false
      ignore_errors: true

    - name: Check if Alacritty configuration file exists
      ansible.builtin.stat:
        path: "{{ alacritty_config }}"
      register: alacritty_config_exists_result
      become: yes
      become_user: "{{ local_user }}"

    - name: Debug Alacritty configuration file
      ansible.builtin.debug:
        msg: "{{ alacritty_config_exists_result }} : coping alacritty configuration file from {{ temp_config_dir }}/alacritty to {{ config_dir }}"
      when: alacritty_config_exists_result.stat.exists == False

    - name: Copy Alacritty configuration file
      ansible.builtin.shell: cp -r "{{ temp_config_dir }}/alacritty" "{{ config_dir }}"
      become: yes
      become_user: "{{ local_user }}"
      when: alacritty_config_exists_result.stat.exists == False

  vars:
    alacritty_ppa: "deb http://ppa.launchpad.net/mmstick76/alacritty/ubuntu focal main"
    alacritty_config: "~/.config/alacritty"
