---
- block:
    - name: Download NVM install script
      get_url:
        url: "{{ nvm_install_script_url }}"
        dest: "/tmp/install_nvm.sh"
        mode: "0755"
      become: yes
      become_user: "{{ local_user }}"

    - name: Run NVM install script
      shell: "bash /tmp/install_nvm.sh"
      args:
        creates: "{{ setup_dir }}/.nvm"
      become: yes
      become_user: "{{ local_user }}"

    - name: Source NVM script
      shell: |
        export NVM_DIR="{{ setup_dir }}/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm --version
      register: nvm_version
      become: yes
      become_user: "{{ local_user }}"

    - name: Debug NVM version
      debug:
        msg: "NVM installed at {{ lookup('env', 'NVM_DIR') }} with version {{ nvm_version.stdout }}"

    - name: Install Node.js using NVM
      shell: |
        export NVM_DIR="{{ setup_dir }}/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install {{ node_version }}
      become: yes
      become_user: "{{ local_user }}"
      when: nvm_version is defined

    - name: Use the installed Node.js version
      shell: |
        export NVM_DIR="{{ setup_dir }}/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm use {{ node_version }}
      become: yes
      become_user: "{{ local_user }}"
      when: nvm_version is defined

  environment:
    NVM_DIR: "{{ setup_dir }}/.nvm"

  vars:
    nvm_install_script_url: "https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh"
